Core/Configuration:
    loggerLevel: 2
    outDir: "../doc"

MenuStyle/Default:
    divClass: sidemenu
    selectedMenuitemClass: menu-selected
    submenuClass: sidemenu-sub
    submenuInHierarchyClass: sidemenu-inhierarchy
File/CopyHandler:
    paths: ["**/*.css", "**/*.js", "**/*.jpg", "**/*.png", "**/*.gif", "**/*.swf"]
